---
title: "Strings and Factors"
output: html_document
date: "2023-10-17"
---


```{r}
library(rvest)
library(p8105.datasets)
library(tidyverse)
```



## Strings and manipulations
```{r}
string_vec = c("My", "name", "is", "Cj")
str_detect(string_vec, "Cj")
str_detect(string_vec, "e")
str_replace(string_vec, "Cj", "CJ")
```

```{r}
new_string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun, actually",
  "it will be fun, i think"
)

str_detect(new_string_vec, "i think")
str_detect(new_string_vec, "^i think") ##^ is line start
str_detect(new_string_vec, "i think$") ##$ is line end
```

```{r}
pumpkin_string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
)

str_detect(pumpkin_string_vec, "Pumpkin")
str_detect(pumpkin_string_vec, "[Pp]umpkin")
```

```{r}
number_string_vec = c(
  "7th inning stretch",
  "1st half soon to begin. Texas won the toss.",
  "she is 5 feet 4 inches tall",
  "3AM - can't sleep :("
)

str_detect(number_string_vec, "[0-9]") 

str_detect(number_string_vec, "^[0-9]")

str_detect(number_string_vec, "^[0-9][a-z]")
```

```{r}
dots_string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(dots_string_vec, "7.11") ## the dot is a wild card and matches anything

```


```{r}
brack_string_vec = c(
  "The CI is [2,5]",
  ":-]",
  ":-[",
  "I found the answer on pages [6-7]"
)

str_detect(brack_string_vec, "\\[") #use backslash to denote special character; backslash itself is also a special character so you need to do it again
str_detect(brack_string_vec, "\\[[0-9]" )


```


## Factors

```{r}
vec_sex = c("male", "male", "female", "female") #just strings!
vec_sex_fac = factor(c("male", "male", "female", "female"))

vec_sex #still has quotations around the strings! bc they are characters
vec_sex_fac ##now there are no quotations, and levels are marked

as.numeric(vec_sex_fac) ##allows us to get the nuemrical representation
vec_sex_fac = fct_relevel(vec_sex_fac, "male")
as.numeric(vec_sex_fac)
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |> 
  slice(-1)

table_marj
```

Needs to be tidied!

```{r}
marj_df = 
  table_marj |> 
  select(-contains("P Value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), "\\(") |> 
  mutate(year = str_replace(year, "\\)", "")) |> 
  mutate(percent = str_replace(percent, "[a-b]", "")) |> 
  mutate(percent = as.numeric(percent)) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))

marj_df

marj_df |>
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## NYC Restaurant Inspections

data("rest_inspec")

```{r}
rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)
```